/**
 * This file was generated by flotiq-api-typegen command
 * Generated at: 2026-08-07T16:53:06.500Z
 */

import {
  DataLink,
  ApiRequest,
  BaseObject,
  SearchParams,
  HydratedSearchResponse,
  InternalGeneratedFormsBase,
  InternalGeneratedForms,
  InternalGeneratedFormsHydrated,
  InternalGeneratedFormsHydratedTwice,
  InternalMediaBase,
  InternalMedia,
  InternalMediaHydrated,
  InternalMediaHydratedTwice,
  InternalPluginSettingsBase,
  InternalPluginSettings,
  InternalPluginSettingsHydrated,
  InternalPluginSettingsHydratedTwice,
  InternalTagBase,
  InternalTag,
  InternalTagHydrated,
  InternalTagHydratedTwice,
  InternalWebhooksBase,
  InternalWebhooks,
  InternalWebhooksHydrated,
  InternalWebhooksHydratedTwice,
} from "@flotiq/flotiq-api-sdk";

type StringWithAutocomplete<T> = T | (string & Record<never, never>);

declare module "@flotiq/flotiq-api-sdk" {
  export type AnySpaceCTD =
    | Event
    | InternalGeneratedForms
    | InternalMedia
    | InternalPluginSettings
    | InternalTag
    | InternalWebhooks;

  export type AnySpaceCTDHydrated =
    | EventHydrated
    | InternalGeneratedFormsHydrated
    | InternalMediaHydrated
    | InternalPluginSettingsHydrated
    | InternalTagHydrated
    | InternalWebhooksHydrated;

  export type AnySpaceCTDHydratedTwice =
    | EventHydratedTwice
    | InternalGeneratedFormsHydratedTwice
    | InternalMediaHydratedTwice
    | InternalPluginSettingsHydratedTwice
    | InternalTagHydratedTwice
    | InternalWebhooksHydratedTwice;

  export type AnySpaceCTDBase =
    | EventBase
    | InternalGeneratedFormsBase
    | InternalMediaBase
    | InternalPluginSettingsBase
    | InternalTagBase
    | InternalWebhooksBase;

  // #region event

  export interface EventBase extends BaseObject<"event"> {
    name: string;
    slug: string;
    image?:
      | Array<DataLink>
      | Array<InternalMedia>
      | Array<InternalMediaHydrated>
      | Array<InternalMediaHydratedTwice>
      | Array<InternalMediaBase>;
    address: string;
    date: string;
    price?: string;
    description?: string;
    excerpt?: string;
    gallery?:
      | Array<DataLink>
      | Array<InternalMedia>
      | Array<InternalMediaHydrated>
      | Array<InternalMediaHydratedTwice>
      | Array<InternalMediaBase>;
  }

  export interface Event extends EventBase {
    image?: Array<DataLink>;
    gallery?: Array<DataLink>;
  }

  export interface EventHydrated extends EventBase {
    image?: Array<InternalMedia>;
    gallery?: Array<InternalMedia>;
  }

  export interface EventHydratedTwice extends EventBase {
    image?: Array<InternalMediaHydrated>;
    gallery?: Array<InternalMediaHydrated>;
  }

  export namespace Event {
    export type FilterableFields = StringWithAutocomplete<
      | "name"
      | "slug"
      | "image"
      | "image[*].type"
      | "image[*].dataUrl"
      | "address"
      | "date"
      | "price"
      | "description"
      | "excerpt"
      | "gallery"
      | "gallery[*].type"
      | "gallery[*].dataUrl"
    >;
  }

  // #endregion

  export interface FlotiqObjectAPI {
    event: ApiRequest<
      Event,
      EventHydrated,
      EventHydratedTwice,
      Event.FilterableFields
    >;

    _generated_forms: ApiRequest<
      InternalGeneratedForms,
      InternalGeneratedFormsHydrated,
      InternalGeneratedFormsHydratedTwice,
      InternalGeneratedForms.FilterableFields
    >;

    _media: ApiRequest<
      InternalMedia,
      InternalMediaHydrated,
      InternalMediaHydratedTwice,
      InternalMedia.FilterableFields
    >;

    _plugin_settings: ApiRequest<
      InternalPluginSettings,
      InternalPluginSettingsHydrated,
      InternalPluginSettingsHydratedTwice,
      InternalPluginSettings.FilterableFields
    >;

    _tag: ApiRequest<
      InternalTag,
      InternalTagHydrated,
      InternalTagHydratedTwice,
      InternalTag.FilterableFields
    >;

    _webhooks: ApiRequest<
      InternalWebhooks,
      InternalWebhooksHydrated,
      InternalWebhooksHydratedTwice,
      InternalWebhooks.FilterableFields
    >;
  }

  export interface FlotiqSearchAPI {
    query<P extends SearchParams>(
      params?: P,
    ): Promise<
      HydratedSearchResponse<
        P,
        AnySpaceCTD,
        AnySpaceCTDHydrated,
        AnySpaceCTDHydratedTwice
      >
    >;
  }
}
