name: PR workflow
on:
  pull_request:

permissions:
  pull-requests: write
  
jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g flotiq-cli
      - run: flotiq import . ${{ secrets.FLOTIQ_API_KEY }}
      - run: yarn install
      - run: yarn build
        env:
          FLOTIQ_API_KEY: ${{ secrets.FLOTIQ_API_KEY }}
          FLOTIQ_API_URL: ${{ secrets.FLOTIQ_API_URL }}
  dependabot:
    needs: test-build
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
